### ISSUE TITLE
Re: Renovate の PR の内容が linter に怒られることを防ぎたい

### ISSUE THREAD

**Issue by sunakan** [sunabak0/akiyadego-kotlin#101]
## 概要

 #93 でマージした内容では、期待した挙動にならなかった

期待する挙動： PR 元が `renovate/**` なら lint-pr しない

## 原因

on.<pull_request|pull_request_target>.<branches|branches-ignore>

の bracnhes|branches-ignore は PR 先へのブランチ名だった

https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
> pull_request イベントと pull_request_target イベントを使用する場合は、特定のブランチを対象とする pull request に対してのみ実行するようにワークフローを構成できます。

> 特定のブランチを対象とする pull request に対して

## 原因が本当か検証

||ブランチ名|
|:---|:---|
|PR From|renovate/sandbox-by-suna|
|PR To|main|

`branches: ["main"]` だと動いた

`branches: ["**", "!main"]` だと動かなかった

このことから、 branches や branches-ignore は pr `先` のブランチ名で判断している（branchs-ignore も試したりした）

詳細は https://github.com/sunabak0/akiyadego-kotlin/pull/100#issuecomment-1367679477

## 対応

GitHub Actions job の実行するしないを制御する場所で、特定のブランチ名を除外する

```yml
jobs:
  lint-pr:
    # 
    # PR 元のブランチ名が renovate/** の場合、実行しない
    #                                                                 
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    steps:
```

この記述で期待通りになることは検証済み

<img width="400" alt="image" src="https://user-images.githubusercontent.com/43210698/210028312-0f5c5613-afde-4544-959f-e6c722b4124a.png">

検証に使ったPR：https://github.com/sunabak0/akiyadego-kotlin/pull/100
