### ISSUE TITLE
ドキュメント用の何かを用意

### ISSUE THREAD

**Issue by sunakan** [sunabak0/akiyadego-kotlin#28]
## 概要

- ドキュメントの導入

## 前提

- 開発環境構築などある程度ドキュメント化していると便利

## 背景

- Docusaurus でドキュメントを管理してみたい

## 対応

- Docusaurus の導入

**Comment by sunakan** [comment]
## 1. 作る

```shell
npx create-docusaurus@latest docs classic
```

作るディレクトリ名：docs
テンプレート名： classic

## 実行結果

**Comment by sunakan** [comment]
## 2. 実行

```shell
cd docs
npm start
```

**Comment by sunakan** [comment]
## 3. GitHub Pages のソースを `GitHub Actions` にする

Settings > Pages > Source > 「GitHub Actions」を選択

<img width="500" alt="image" src="https://user-images.githubusercontent.com/43210698/208182057-71649b27-f375-481f-b661-d8ad2781e5dc.png">

**Comment by sunakan** [comment]
## 4. 一時的にGitHub Pages へのデプロイブランチを `All branches` にする

Settings > Environments > 「github-pages」があるのでクリック > Deployment branches > `All branches` にする

理由：一旦デプロイができるかを確かめるため

PRがマージされたら、適宜 `Protected branches` に戻す 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/43210698/208183813-9427ddd6-09e6-4e8a-b01c-1695c6f1315f.png">

**Comment by sunakan** [comment]
## 5. GitHub Actions でデプロイするフローを組む

デプロイ周りでお世話になるのは2つの Action

- actions/upload-pages-artifact@v1
  - https://github.com/actions/upload-pages-artifact
- actions/deploy-pages@v1
  - https://github.com/actions/deploy-pages#usage を参考


```yaml
#
# ドキュメントを GitHub Pages に deploy する
#
---
name: Deploy docs

'on':
  push:

jobs:
  #
  # 静的ページを build
  #
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: nodejsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 依存ライブラリのインストール
        run: npm install
        working-directory: ./docs
      - name: npm run build
        run: npm run build
        working-directory: ./docs
      - name: build 結果をを成果物 ( アーティファクト ) にする
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/build/

  #
  # GitHub Pages にデプロイ
  #
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 成果物 ( アーティファクト ) を GitHub Pages にデプロイ
        id: deployment
        uses: actions/deploy-pages@v1
```
