### ISSUE TITLE
lint PR で PR を修正して、job を再実行させても PR の変更が読み込まれない

### ISSUE THREAD

**Issue by Msksgm** [sunabak0/akiyadego-kotlin#33]
## 概要

lint PR で PR を修正して、job を再実行させても PR の変更が読み込まれない問題が発生した。
新しいコミットが push されたら更新されるが、PR の lint をするためにリモートブランチに push しないといけない。

**Comment by sunakan** [comment]
もしかしたら、 PR Title/Body の修正に対して発火させたらいけそう

```yaml
'on':
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
```

> job を再実行させても

job が勝手に再実行されるため、解決できるかもしれない

## pull_request のデフォルト
- opend
- reopend
- synchronize
  - push された時など ブランチの HEAD が変わった時

https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request

## edited を追加

それぞれの意味は以下

https://docs.github.com/ja/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
