### ISSUE TITLE
【調査タスク】 SpringBoot で Cookie を操作方法を学ぶ

### ISSUE THREAD

**Issue by sunakan** [sunabak0/akiyadego-kotlin#74]
- Cookieに保存できる
- Cookieを削除できる
- Cookieを更新できる

## 触り

[Spring BootでHTTPセッションをあつかう3つのパターン](https://www.memory-lovers.blog/entry/2018/02/04/171013)

によると、

- セッション属性(`@SessionAttribute`)
- セッションスコープBean
- Http Session

の3種があるらしい

**Comment by sunakan** [comment]
OpenAPI Generator + Kotlin SpringBootではまだっぽい

### https://github.com/OpenAPITools/openapi-generator/issues/12976

↓がうまく生成されない

```yaml
securitySchemes:
  cookieAuth:
        type: apiKey
        in: cookie
        name: token
```


### https://github.com/OpenAPITools/openapi-generator/issues/10008

https://gist.github.com/puneetugru/ec65183b4ad2da3ee8a7b43def2eea4a


### コミット

貢献するための勉強が必要そう
