### ISSUE TITLE
Renovate の PR の内容が linter に怒られることを防ぎたい

### ISSUE THREAD

**Issue by sunakan** [sunabak0/akiyadego-kotlin#93]
## 概要

https://github.com/sunabak0/akiyadego-kotlin/pull/87#issuecomment-1363212476

等で PR 内容が

```
21:1    error  Line 21 sentence length(119) exceeds the maximum sentence length of 100.
Over 19 characters  ja-technical-writing/sentence-length
28:1    error  Line 28 sentence length(111) exceeds the maximum sentence length of 100.
Over 11 characters  ja-technical-writing/sentence-length
55:248  error  This sentence exceeds the maximum count of comma. Maximum is 3            ja-technical-writing/max-comma
63:1    error  Line 63 sentence length(112) exceeds the maximum sentence length of 100.
Over 12 characters  ja-technical-writing/sentence-length
```

と怒られる

なんとかしたい

**Comment by sunakan** [comment]
renovateはブランチ名に命名規則があるので、それで pr に対して lint をかけないでも良さそう

[GitHub Actions のワークフロー構文 > 例: ブランチの除外](https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#%E4%BE%8B-%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%AE%E9%99%A4%E5%A4%96)

例だと以下の感じ

```yaml
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches-ignore:    
      - 'mona/octocat'
      - 'releases/**-alpha'
```

**Comment by sunakan** [comment]
```yml
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'renovate/*'
```

とかでいけない？とか

**Comment by sunakan** [comment]
GitHubの検索キーワード「extension:yml branches-ignore renovate」

https://github.com/search?q=extension%3Ayml+branches-ignore+renovate

でを見ると '*' は2個が一般的なのかもしれない

```yaml
on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
```
